machines = {
	"master" => {"memory" => "512", "cpu" => "1", "image" => "bento/ubuntu-22.04"},
	"node01" => {"memory" => "512", "cpu" => "1", "image" => "bento/ubuntu-22.04"},
	"node02" => {"memory" => "512", "cpu" => "1", "image" => "bento/ubuntu-22.04"},
	"node03" => {"memory" => "512", "cpu" => "1", "image" => "bento/ubuntu-22.04"}
}

Vagrant.configure("2") do |config|
	machines.each_with_index do |(name, config), index|
		config.vm.define "#{name}" do |machine|
			machine.vm.box = "#{config["image"]}"
			machine.vm.hostname = "#{name}"
			machine.vm.network "private_network", ip: "10.0.50.#{index+10}"
			machine.vm.provider "virtualbox" do |vb|
				vb.name = "#{name}"
				vb.memory = config["memory"]
				vb.cpus = config["cpu"]
			end
			machine.vm.provision "shell", path: "install-docker.sh"
			if name == "master"
				machine.vm.provision "shell", inline: <<-SHELL
					docker swarm init --advertise-addr 10.0.50.10
					docker swarm join-token worker -q > /vagrant/token.txt
				SHELL
			else
				machine.vm.provision "shell", inline: <<-SHELL
					docker swarm join --token $(cat /vagrant/token.txt) 10.0.50.10:2377
				SHELL
			end
		end
	end
end