version: '3.9'

services:
  # Define o serviço Apache
  apache:
    # Usa a imagem mais recente do Apache HTTP Server
    image: httpd:latest

    # Define o nome do container
    container_name: my-website

    # Mapeia a porta 80 do container para a porta 80 do host
    ports:
      - '8080:80'

    # Mapeia o diretório 'website' do host para o diretório de documentos do Apache no container
    volumes:
      - ./website:/usr/local/apache2/htdocs
